# fly.toml file generated for plmography-spring on 2023-02-17T00:10:40+09:00

app = "plmography-spring"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 5432
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80
http_options = { response = { headers = { access-control-allow-origin = "*", to-remove = false } } }

[[services.ports]]
handlers = ["pg_tls"]
port = 5432

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
